#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : virtualenv
Version  : 13.1.2
Release  : 8
URL      : https://pypi.python.org/packages/source/v/virtualenv/virtualenv-13.1.2.tar.gz
Source0  : https://pypi.python.org/packages/source/v/virtualenv/virtualenv-13.1.2.tar.gz
Summary  : Virtual Python Environment builder
Group    : Development/Tools
License  : MIT
Requires: virtualenv-bin
Requires: virtualenv-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
virtualenv
==========
.. image:: https://pypip.in/v/virtualenv/badge.png
:target: https://pypi.python.org/pypi/virtualenv

%package bin
Summary: bin components for the virtualenv package.
Group: Binaries

%description bin
bin components for the virtualenv package.


%package python
Summary: python components for the virtualenv package.
Group: Default

%description python
python components for the virtualenv package.


%prep
%setup -q -n virtualenv-13.1.2

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/virtualenv
/usr/bin/virtualenv-2.7
/usr/bin/virtualenv-3.4

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
